# Generated by Django 4.2.3 on 2023-07-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='строка'),
        ),
    ]
